controller_manager:
  ros__parameters:
    update_rate: 20
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    m4_proposal_controller:
      type: forward_command_controller/ForwardCommandController

m4_proposal_controller:
  ros__parameters:
    joints: [shoulder_pitch_joint]
    interface_name: position
