<?xml version="1.0"?>
<package format="3">
  <name>motionbrain_ros2_control_mock</name>
  <version>0.1.0</version>
  <description>Optional ros2_control mock hardware demo for MotionBrain.</description>
  <maintainer email="ParkJsoo@users.noreply.github.com">Jeongsoo Park</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>controller_manager</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>ros2_control</exec_depend>
  <exec_depend>ros2_control_test_assets</exec_depend>
  <exec_depend>ros2_controllers</exec_depend>
  <exec_depend>ros2controlcli</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
